### ISSUE TITLE
latest boo does not build with mono 1.1.9.2

### ISSUE THREAD

**Issue by mattmc3** [boo-dotnet/boo-codehaus-archive#529]
| Field | Value |
|---|---|
| Type | Bug |
| Status | Closed |
| Priority | Major |
| Resolution | Fixed |
| Reporter | G�tz Waschk |
| Assignee | Unassigned |
| Affects | 0.7 |
| Fix for | None |
| Components | Runtime (Boo.Lang) |
| Created | 2005-10-20T03:37-0500 |
| Updated | 2005-10-20T06:30-0500 |
| Resolved | 2005-10-20T06:30-0500 |

## Description

boo 0.7.0 and svn release 1942 both fail to build with this error:

Boo.Lang.Interpreter:

 [booc] Compiling 4 file(s) to /tmp/BUILD/boo/build/Boo.Lang.Interpreter.dll.

 [booc] /tmp/BUILD/boo/src/Boo.Lang.Interpreter/AbstractInterpreter.boo(263,35): BCE0019: 'GetOptionalEntity' is not a member of 'Boo.Lang.Compiler.TypeSystem.TypeSystemServices'.

 [booc] 1 error(s).

BUILD FAILED - 1 non-fatal error(s), 1 warning(s)

/tmp/BUILD/boo/default.build(109,4):

boo compilation error

## Comments (1)

---

### Rodrigo B. de Oliveira, 20/Oct/05 6:30 AM

Remove the old version from the GAC first.

## Provenance

- <http://web.archive.org/web/20150517103827id_/https://jira.codehaus.org/browse/BOO-529>
- <http://web.archive.org/web/20150520081222id_/https://jira.codehaus.org/browse/BOO-529?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel>
